package com.example.visa.telegram.utils;

public enum BotState {
    IDLE,
    AWAITING_TRAVEL_PURPOSE,
    AWAITING_TRAVEL_DATE,
    AWAITING_PASSPORT_NUMBER,
    AWAITING_NAME,
    AWAITING_SURNAME,
    AWAITING_TURKISH_IDENTIFICATION_NUMBER,
    AWAITING_BIRTH_YEAR,
    AWAITING_PHONE_NUMBER,
    AWAITING_EMAIL,
    AWAITING_FOR_USER_ACCEPTION,
    READY_FOR_APPLICATION,
    SUBMITTED
}